git mv 00-Master.ppt en
git mv 00-Braile-Slide-Summaries-01-10.doc en
git mv intro-wrapup.ppt en
git mv Pythonlearn-01-Intro.ppt en
git mv Pythonlearn-02-Expressions.ppt en
git mv Pythonlearn-03-Conditional.ppt en
git mv Pythonlearn-04-Functions.ppt en
git mv Pythonlearn-05-Iterations.ppt en
git mv Pythonlearn-06-Strings.ppt en
git mv Pythonlearn-07-Files.ppt en
git mv Pythonlearn-08-Lists.ppt en
git mv Pythonlearn-09-Dictionaries.ppt en
git mv Pythonlearn-10-Tuples.ppt en
git mv Pythonlearn-11-Regex-Handout.txt en
git mv Pythonlearn-11-Regex.ppt en
git mv Pythonlearn-12-HTTP.ppt en
git mv Pythonlearn-13-WebServices.ppt en
git mv Pythonlearn-13-WebServices.ppt en
git mv Pythonlearn-14-Objects.ppt en
git mv Pythonlearn-15-Database-Handout.txt en
git mv Pythonlearn-15-Databases.ppt en
git mv Pythonlearn-16-Data-Viz.ppt en
git status